language: ruby
cache: bundler
sudo: false
rvm:
  - 1.9.3-p551
  - 2.0.0-p648
  - 2.1.9
  - 2.2.6
  - 2.3.3
  - 2.4.0
matrix:
  include:
  - rvm: rbx-3.62
    dist: trusty # Ubuntu 14.04 (trusty)
  allow_failures:
    - rvm: rbx-3.62
    - rvm: 1.9.3-p551
    - rvm: 2.0.0-p648